# Generated by Django 4.2.15 on 2024-09-16 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text="Enter the company's name.", max_length=100)),
                ('tagline', models.CharField(help_text='Enter a tagline for the company.', max_length=255)),
                ('details', models.TextField(help_text='Enter a detailed description of the company.')),
                ('reference_link', models.URLField(default='', help_text='Enter the link to the company.')),
                ('image', models.ImageField(help_text='Upload an image of the company.', null=True, upload_to='website.File/bytes/filename/mimetype')),
                ('reference_link_label', models.CharField(help_text='Enter the label for the reference link.', max_length=100)),
                ('show_chart', models.BooleanField(default=False, help_text='Indicates if the chart should be shown.')),
                ('connect', models.PositiveSmallIntegerField(default=0, help_text='Connection rating (max 100).', validators=[django.core.validators.MaxValueValidator(100)])),
                ('take_picture', models.PositiveSmallIntegerField(default=0, help_text='Rating for picture-taking feature (max 100).', validators=[django.core.validators.MaxValueValidator(100)])),
                ('view', models.PositiveSmallIntegerField(default=0, help_text='Rating for viewing feature (max 100).', validators=[django.core.validators.MaxValueValidator(100)])),
                ('opinion', models.TextField(help_text='Opinion on the company.')),
                ('additional_details', models.TextField(help_text='Additional details about the company.')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
    ]
