# Generated by Django 4.2.15 on 2024-09-16 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='connect',
            field=models.PositiveSmallIntegerField(default=0, help_text='Connection rating (e.g., compatibility score, max 100).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='take_picture',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rating for picture-taking feature (max 100).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='view',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rating for viewing feature (max 100).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
